CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

PROJECT(UPP_SP2)

SET(CMAKE_CXX_STANDARD 23)

FILE(GLOB_RECURSE src src/*.cpp src/*.h src/*.hpp)

SET(USE_SSL OFF CACHE BOOL "Use SSL")

IF(USE_SSL)
	ADD_DEFINITIONS(-DUSE_SSL)
	FIND_PACKAGE(OpenSSL REQUIRED)
	INCLUDE_DIRECTORIES("${OPENSSL_INCLUDE_DIR}")
ENDIF()

FIND_PACKAGE(MPI REQUIRED)

INCLUDE_DIRECTORIES("dep/cpp-httplib")

ADD_EXECUTABLE(UPP-SP2 ${src})

TARGET_INCLUDE_DIRECTORIES(UPP-SP2 PRIVATE ${MPI_CXX_INCLUDE_DIRS})
TARGET_LINK_LIBRARIES(UPP-SP2 ${MPI_CXX_LIBRARIES})

IF(USE_SSL)
	TARGET_LINK_LIBRARIES(UPP-SP2 OpenSSL::SSL OpenSSL::Crypto)
ENDIF()
